# Generated by Django 4.0.1 on 2022-01-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CopyrightHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilePath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name="Holder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=127, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spdx_license_key", models.CharField(max_length=127, unique=True)),
                ("spdx_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="LicenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Licenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, unique=True)),
                (
                    "file_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="quenv.filepath"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_created=True)),
                ("has_errors", models.BooleanField()),
                (
                    "copyright_holders_keys",
                    models.ManyToManyField(
                        through="quenv.CopyrightHolder", to="quenv.Holder"
                    ),
                ),
                (
                    "licenses_keys",
                    models.ManyToManyField(
                        through="quenv.Licenses", to="quenv.License"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=15)),
                (
                    "date_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="quenv.scandate"
                    ),
                ),
                (
                    "package_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="quenv.package"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scandate",
            name="packages_keys",
            field=models.ManyToManyField(through="quenv.Version", to="quenv.Package"),
        ),
        migrations.AddField(
            model_name="licenses",
            name="date_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.scandate"
            ),
        ),
        migrations.AddField(
            model_name="licenses",
            name="file_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.filepath"
            ),
        ),
        migrations.AddField(
            model_name="licenses",
            name="license_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.license"
            ),
        ),
        migrations.AddField(
            model_name="licenses",
            name="score_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.score"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="category_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.licensecategory"
            ),
        ),
        migrations.AddField(
            model_name="copyrightholder",
            name="date_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.scandate"
            ),
        ),
        migrations.AddField(
            model_name="copyrightholder",
            name="file_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.filepath"
            ),
        ),
        migrations.AddField(
            model_name="copyrightholder",
            name="holder_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="quenv.holder"
            ),
        ),
    ]
