# Generated by Django 4.0.1 on 2022-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quenv", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filepath",
            name="path",
            field=models.CharField(max_length=511, unique=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="spdx_url",
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name="version",
            name="version",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
