# Generated by Django 3.0.8 on 2020-07-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quenv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='environment_name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Environment Name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_name',
            field=models.CharField(max_length=127, unique=True, verbose_name='License Name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(max_length=63, unique=True, verbose_name='Package Name'),
        ),
    ]
