# Generated by Django 4.0.1 on 2022-01-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quenv', '0002_alter_filepath_path_alter_license_spdx_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scandate',
            old_name='datetime',
            new_name='start_timestamp',
        ),
    ]
