# Generated by Django 3.0.8 on 2020-08-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quenv', '0002_auto_20200731_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'View by Date', 'verbose_name_plural': 'View by Date'},
        ),
        migrations.AlterModelOptions(
            name='incrementalchanges',
            options={'verbose_name': 'View Changes', 'verbose_name_plural': 'View Changes'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Panorama', 'verbose_name_plural': 'Panorama'},
        ),
    ]
